name: CD
on: pull_request

jobs:
  cd:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: "pipenv"
      - uses: tiagovrtr/actions-pipenv@v1
        with:
          pipenv-version: ${{ matrix.pipenv-version }}
      - run: pipenv run mkdocs gh-deploy
